apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: qualitygroup/myapp:v1
    ports:
     - containerPort: 8080
    command: ["java", "-jar", "/app.jar"]  # Adjust jar path if needed

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080        # Port exposed inside cluster
    targetPort: 8080  # Container's listening port
    nodePort: 30080   # External port (must be 30000-32767)
  type: NodePort

