---
name: buiding the spring petclinic project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          security-events: write
          actions: read
        steps:
            - name: "checkout the code"
              uses: actions/checkout@v5
            - name: "install java jdk"
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '21'
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: java
            - name: "build the java package"
              run: mvn package
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                name: java-app
                path: target/*.jar
            - name: Upload JUnit Test Results
              uses: actions/upload-artifact@v4
              with:
                name: junit-results
                path: target/surefire-reports/*.xml
            # - name: Perform CodeQL Analysis
            #   uses: github/codeql-action/analyze@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
            - name: Build Docker Image
              run: docker build -f Image/Dockerfile -t ${{ secrets.USERNAME }}/myapp:v1 .
            - name: Docker Push Image
              run: docker push ${{ secrets.USERNAME }}/myapp:v1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            # - name: Terraform Format
            #   run: terraform fmt -check
            #   working-directory: ./infrastructure

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Terraform  Init
              run: terraform init
              working-directory: ./infrastructure

            # - name: Terraform plan
            #   run: terraform plan
            #   working-directory: ./infrastructure

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: ./infrastructure
          
            - name: Install kubectl
              run: |
               curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
               chmod +x kubectl
               sudo mv kubectl /usr/local/bin/

            - name: Update kubeconfig for EKS
              run: |
               aws eks update-kubeconfig --region ap-south-1 --name demo-eks-cluster

            - name: Deploy manifest
              run: |
               kubectl apply -f deployment.yaml
              working-directory: manifest
          
